BEGIN TRANSACTION;
DROP TABLE IF EXISTS `users`;
CREATE TABLE IF NOT EXISTS `users` (
	`id`	INTEGER PRIMARY KEY AUTOINCREMENT,
	`email`	TEXT NOT NULL UNIQUE,
	`name`	TEXT NOT NULL,
	`username`	TEXT NOT NULL UNIQUE,
	`password`	TEXT NOT NULL,
	`avatar`	TEXT DEFAULT "default.jpg",
	`profile_bio`	TEXT,
	`created_at`	DATETIME NOT NULL DEFAULT (datetime(CURRENT_TIMESTAMP))
);

DROP TABLE IF EXISTS `posts`;
CREATE TABLE IF NOT EXISTS `posts` (
	`id`	INTEGER PRIMARY KEY AUTOINCREMENT,
	`user_id`	TEXT NOT NULL,
	`image`	TEXT NOT NULL UNIQUE,
	`description`	TEXT NOT NULL,
	`created`	DATETIME NOT NULL DEFAULT (datetime(CURRENT_TIMESTAMP)),
  FOREIGN KEY (`user_id`) REFERENCES users(`id`) ON DELETE CASCADE
);

DROP TABLE IF EXISTS `likes`;
CREATE TABLE IF NOT EXISTS `likes` (
	`id`	INTEGER PRIMARY KEY AUTOINCREMENT,
	`post_id`	INTEGER,
	`user_id`	INTEGER,
  FOREIGN KEY (`user_id`) REFERENCES users(`id`) ON DELETE CASCADE,
  FOREIGN KEY (`post_id`) REFERENCES posts(`id`) ON DELETE CASCADE
);
COMMIT;
